DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY NOT NULL,
    user_name VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
);

DROP TABLE IF EXISTS tokens;

CREATE TABLE tokens(
    id SERIAL PRIMARY KEY NOT NULL,
    access_token VARCHAR(500) NOT NULL,
    user_id SERIAL NOT NULL REFERENCES users (id),
);
